baseURL = 'https://example.org/'
languageCode = 'vi'
title = 'Black Cat'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 15
disableHugoGeneratorInject = false
enableEmoji = true
publishdir="uroboros-k.github.io"
[params]
ava = "/img/cat.png"
owner ="Mr. Balck Cat"
talk = "Hello guys &#128075; I'm a cool Learner."
blogSection = ["blog"]
description = "Cat"
favicon = "/img/logo.ico"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4



[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"
  
